### ISSUE TITLE
Getting error undefiend _c

### ISSUE THREAD

**Issue by muazzamazaz** [moreta/vue-search-select#164]
Getting error:
```
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.ModelSelectvue_type_template_id_828ed82c_render (ModelSelect.vue?3da4:1:66)
    at renderComponentRoot (runtime-core.esm-bundler.js:890:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5602:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5716:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5730:9)
    at mountComponent (runtime-core.esm-bundler.js:5512:9)
    at processComponent (runtime-core.esm-bundler.js:5470:17)
    at patch (runtime-core.esm-bundler.js:5060:21)
    at mountChildren (runtime-core.esm-bundler.js:5256:13)

```
```
<script setup>
import { Head, Link, useForm } from '@inertiajs/inertia-vue3';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';
import {TheMask} from 'vue-the-mask';
import axios from 'axios';
import 'vue-search-select/dist/VueSearchSelect.css';
import { ModelSelect } from 'vue-search-select';

</script>

<template>
              <model-select :options="drivers"
                                v-model="form.driver"
                                placeholder="select driver">
         </model-select>
</template>
```

**Comment by het-t** [comment]
facing the same issue !
