### ISSUE TITLE
error on enterItem

### ISSUE THREAD

**Issue by shinnlu** [moreta/vue-search-select#191]
i found a error when i press enter in the select.

i have many input field in my form, i want to press enter to focus to next field, when i press enter to focus to model-list-select field, the error message:
```
index-85856991.js:1 TypeError: Cannot read properties of undefined (reading 'disabled')
    at Object.enterItem (index-85856991.js:5:23529)
    at Proxy.enterItem (index-85856991.js:5:25740)
    at index-85856991.js:5:27046
    at index-85856991.js:1:53152
    at index-85856991.js:1:53373
    at index-85856991.js:1:51251
    at _t (index-85856991.js:1:12673)
    at Fe (index-85856991.js:1:12751)
    at Fe (index-85856991.js:1:12851)
    at HTMLInputElement.n (index-85856991.js:1:51036)
```
the error occur on [official demo site](https://vue-search-select.netlify.app/#/model)

# reprocedure the problem
open [official demo site](https://vue-search-select.netlify.app/#/model)
focus on any one of select element, press enter.

**Comment by yatsenkoleg-spiralsoft** [comment]
just to avoid getting an error
```
<model-select
  ref="select"
  :options="accountManagersOptions"
  v-model="apiCallData.ACCOUNT_MANAGER_FULL_NAME.value"
  placeholder=""

  @keyup.enter.capture.stop="console.log('111');"

/>
```
